### ISSUE TITLE
Mlflow database

### ISSUE THREAD

**Issue by karbyshevds** [odahu/odahu-trainer#21]
https://www.mlflow.org/docs/latest/tracking.html#storage

Tasks:
* [x] ~~two variants of the MLFlow deployment (with\w.o database)~~ Database should be used for backend storage
* [x] MLFlow DB upgrade
* [x] supports in cluster PG deployment as database for MLFlow. Database in PG is already present
* [x] ~~suppots object storage configuration for MLFlow artifact store~~ This subtask applies to #10

**Comment by easokol** [comment]
PR: #27
